{{- if and $.Values.AWX.enabled $.Values.AWX.postgres.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "postgres.secretName" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - remoteRef:
        key: awx
        property: dbPassword
      secretKey: postgresqlPassword
  target:
    name: {{ include "postgres.secretName" . }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        password: "{{ `{{ .postgresqlPassword }}` }}"
        host: {{ .Values.AWX.postgres.host }}
        port: {{ .Values.AWX.postgres.port | quote }}
        database: {{ .Values.AWX.postgres.dbName }}
        username: {{ .Values.AWX.postgres.username }}
        sslmode: {{ .Values.AWX.postgres.sslmode }}
        target_session_attrs: {{ .Values.AWX.postgres.target_session_attrs | default "any" }}
        type: {{ .Values.AWX.postgres.type }}
      engineVersion: v2
      mergePolicy: Replace
{{- end }}
