apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tempo-storage-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: tempo-storage-secret
    creationPolicy: Owner
  data:
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/minio
        property: postgres_user
    - secretKey: S3_SECRET_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/minio
        property: postgres_password
