apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tempo-storage-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: tempo-storage-secret
    creationPolicy: Owner
  data:
    # Use AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY - Tempo reads these natively
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/minio
        property: postgres_user
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/minio
        property: postgres_password
