apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: grafana-oauth-secret
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/grafana
        property: client_id
    - secretKey: client_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/grafana
        property: client_secret
    - secretKey: auth_url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/grafana
        property: auth_url
    - secretKey: token_url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/grafana
        property: token_url
    - secretKey: api_url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/grafana
        property: api_url
