apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevirt-manager
  namespace: {{ .Values.namespace }}
  labels:
    app: kubevirt-manager
    app.kubernetes.io/name: kubevirt-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kubevirt-manager
  template:
    metadata:
      labels:
        app: kubevirt-manager
        app.kubernetes.io/name: kubevirt-manager
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: kubevirt-manager
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
            {{- if .Values.oauth.enabled }}
            - name: oauth-config
              mountPath: /etc/nginx/conf.d/oauth.cfg
              subPath: oauth.cfg
            {{- end }}
            {{- if .Values.auth.enabled }}
            - name: auth-config
              mountPath: /etc/nginx/conf.d/auth.cfg
              subPath: auth.cfg
            - name: auth-secret
              mountPath: /etc/nginx/conf.d/auth.htpasswd
              subPath: auth.htpasswd
            {{- end }}
            {{- if .Values.prometheus.enabled }}
            - name: prometheus-config
              mountPath: /etc/nginx/conf.d/prometheus.cfg
              subPath: prometheus.cfg
            {{- end }}
      volumes:
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
        {{- if .Values.oauth.enabled }}
        - name: oauth-config
          configMap:
            name: kubevirt-manager-oauth
            optional: true
        {{- end }}
        {{- if .Values.auth.enabled }}
        - name: auth-config
          configMap:
            name: kubevirt-manager-auth
            optional: true
        - name: auth-secret
          secret:
            secretName: kubevirt-manager-auth
            optional: true
        {{- end }}
        {{- if .Values.prometheus.enabled }}
        - name: prometheus-config
          configMap:
            name: kubevirt-manager-prometheus
            optional: true
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
