{{- if and .Values.cdi.enabled .Values.cdi.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cdi-uploadproxy
  namespace: cdi
  annotations:
    {{- with .Values.cdi.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.cdi.ingress.className }}
  {{- if .Values.cdi.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.cdi.ingress.host | quote }}
      secretName: {{ .Values.cdi.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.cdi.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cdi-uploadproxy
                port:
                  number: 443
{{- end }}
