apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 4mcs4djs-workload
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "web={{ .Values.imageRepository }}"
    argocd-image-updater.argoproj.io/web.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: main
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: {{ .Values.chartPath }}
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
  destination:
    name: in-cluster
    namespace: {{ .Values.namespace }}
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.spec.containers[].image
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
      - SkipDryRunOnMissingResource=true
