replicaCount: 1
ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    # Homepage dashboard integration
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Kroki"
    gethomepage.dev/description: "Diagrams as Code"
    gethomepage.dev/group: "Tools"
    gethomepage.dev/icon: "kroki.png"
    gethomepage.dev/href: "https://kroki.ops.techsecom.io"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/enabled: "true"
  hosts:
  - host: kroki.ops.techsecom.io
    paths:
    - /
  tls:
  - secretName: kroki-tls
    hosts:
    - kroki.ops.techsecom.io

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

bpmn:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

diagramsnet:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

excalidraw:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

mermaid:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
